### ISSUE TITLE
Add Linux compatibility

### ISSUE THREAD

**Issue by joshghent** [jammie1903/project-builder#8]
In theory java should be cross platform but for some reason when booting under Ubuntu it does not work!

**Comment by joshghent** [comment]
So I've discovered @jammie1903 - the actual issue seems to be it cannot find a class at the runtime. On windows, when running on the exe, it works perfectly. But on windows, if you try and start the jar directly it does not work. The error is as follows

```
Error: Could not find or load main class com.jamie.builder.Main
Caused by: java.lang.NoClassDefFoundError: javafx/application/Application
```

**Comment by jammie1903** [comment]
curious, the jar should contain the main class, ill have to have a look in to this at some point
